name: Profile-3D-Contrib
description: Generate a 3D contribution calendar from GitHub, GitLab and Forgejo activity
author: yoshi389111

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'box'
  color: 'green'
